### ISSUE TITLE
There is fake space in number fields

### ISSUE THREAD

**Issue by hugobernard** [Kozea/formol#3]
Phone number, bank account...

**Comment by paradoxxxzero** [comment]
We have this solution for now: https://kozea.github.io/formol/?knob-Fake%20delay%20%28ms%29=10&knob-I18n=en&selectedKind=Formatters&selectedStory=Item%20to%20field%20formatter&full=0&addons=1&stories=1&panelRight=1&addonPanel=dump247%2Fstate%2Fpanel

A better one could be using something like that: https://github.com/insin/react-maskedinput
