### ISSUE TITLE
Select Menu down arrow does not refresh/move list

### ISSUE THREAD

**Issue by M1K3Yio** [Kozea/formol#39]
If you open any of your Select Menu's in your storybook and open the list and start pressing the down arrow, once you get to the end it won't auto load the view of the list items.  From what I can tell this is due to React-Window and rendering as the MenuList component for React-Select.

**Comment by paradoxxxzero** [comment]
Hum yes, the react-window integration is not quite perfect yet. I'm planning to rework it again with the new DynamicSizeList (https://github.com/bvaughn/react-window/issues/6) and I'll try to make the keyboard works as intended.

Thanks for the report
