### ISSUE TITLE
How to apply styles

### ISSUE THREAD

**Issue by stolinski** [Kozea/formol#44]
I've followed the docs here: https://kozea.github.io/formol/?path=/story/home--home

Using like this: 
```
import Formol, {Field} from 'formol'

const onSubmit = ({ login, password }) =>
  doLogin(login, password)

<Formol onSubmit={onSubmit}>
  <Field>Login</Field>
  <Field type="password-strength">Password</Field>
</Formol>
```

and none of the input styling is there. I checked the repo for CSS files to add, but there is only scss and no compiled css. Since I'm not using scss, I'm not sure how to proceed with using this library.

**Comment by paradoxxxzero** [comment]
My mistake, you have to import the css indeed.
For the default style:
```js
import 'formol/lib/default.css'
```

For the clean style:
```js
import 'formol/lib/clean.css'
```
You can also directly import the sass file if you are using sass:

```sass
@import ~formol/src/sass/default
```

**Comment by paradoxxxzero** [comment]
Updated at bottom of https://kozea.github.io/formol/?path=/story/home--home

**Comment by stolinski** [comment]
Thank you!
