### ISSUE TITLE
create-react-app compatibility

### ISSUE THREAD

**Issue by PabloSzx** [Kozea/formol#45]
How can I do the webpack rules if I'm using https://github.com/facebook/create-react-app

**Comment by paradoxxxzero** [comment]
I don't think **CRA** allows you to change the webpack config.
There are several projects that try to workaround this, you can try [craco](https://github.com/sharegate/craco), [react-app-rewired](https://github.com/timarney/react-app-rewired), [rescripts](https://github.com/harrysolovay/rescripts).

**Comment by PabloSzx** [comment]
I understand that fact, but by this issue i mean, there is no direct compatibility for CRA then?

**Comment by pkalisiewicz** [comment]
If there is no option to add it to the create-react-app, is there any starter project with pre-configured webpack which we can use to play around, apart of the storybook demo?

**Comment by paradoxxxzero** [comment]
Here you go https://github.com/Kozea/formol_starter_pack

**Comment by pkalisiewicz** [comment]
It is actually possible to attach it to the create-react-app.
Instead of importing
```
import Formol, { Field } from 'formol';
```


you need to import a precompiled version

```
import Formol, { Field } from 'formol/lib/formol';
```

**Comment by paradoxxxzero** [comment]
formol use date-fns 2 (which is still not stable...), so you want to:
```sh
yarn add date-fns@next
```

**Comment by trujic1000** [comment]
I started project with CRA and used [react-app-rewired](https://github.com/timarney/react-app-rewired) to make configure webpack and be able to use formol.

https://github.com/trujic1000/formol-starter-pack
