### ISSUE TITLE
Add TypeScript typings (d.ts)

### ISSUE THREAD

**Issue by today-** [Kozea/formol#51]
Now it's not possible to use Formol with TypeScript

**Comment by paradoxxxzero** [comment]
If someone wants to make them and posts them somewhere like http://definitelytyped.org/ I'll be glad to add a link in the readme and on the storybook.
Personally, I'm not interested in TypeScript for several reasons, so I won't write them, nor maintain them.

**Comment by today-** [comment]
Type deifinitions for this package are now located in `@types/formol`
https://www.npmjs.com/package/@types/formol
