### ISSUE TITLE
Soucemap

### ISSUE THREAD

**Issue by Gnilherk** [Kozea/formol#55]
Quick question: 
Is there a sourcemap available? I'm trying to add my own types and I get wired errors. 
I can't really debug them since the compiled code is used.

How would I be able to get the sourcemap for the current version of formol so that debugging would be easier?

THx

**Comment by gerwinbrunner** [comment]
Any update on this?

**Comment by paradoxxxzero** [comment]
I added source maps to builds, I'll release a new version quickly, let me now if it works for you

**Comment by paradoxxxzero** [comment]
I pushed it as v2.5.12
